name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Set Docker tag
      run: echo "DOCKER_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build and push Docker image with GitHub cache
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: mcagan/haritapark:${{ env.DOCKER_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
